const data = {
  products: [
    {
      _id: 1,
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: 2,
      name: 'Adidas Slim Shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adida',
      rating: 4,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: 3,
      name: 'Lacoste Free Shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 30,
      brand: 'lacoste',
      rating: 4.8,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: 4,
      name: 'Columbia Slim Pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 120,
      countInStock: 15,
      brand: 'Columbia',
      rating: 4,
      numReviews: 8,
      description: 'high quality product',
    },
    {
      _id: 5,
      name: 'Puma Slim Pant',
      category: 'Pants',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 0,
      brand: 'Puma',
      rating: 3.4,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: 6,
      name: 'Adidas Slim Pant',
      category: 'Pants',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 22,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 7,
      description: 'high quality product',
    },
    {
      _id: 7,
      name: 'Columbia Slim Pant',
      category: 'Pants',
      image: '/images/p7.jpg',
      price: 120,
      countInStock: 19,
      brand: 'Columbia',
      rating: 4,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: 8,
      name: 'Columbia Slim Shirt',
      category: 'Shirts',
      image: '/images/p8.jpg',
      price: 220,
      countInStock: 1,
      brand: 'Columbia',
      rating: 4,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};

export default data;
